# ==========================================
# DESAFIO DATA ENGINEER CLAVIS
# Configuração de Pipelines do Logstash
# ==========================================

# Pipeline principal - roteia todos os dados de criptomoedas
- pipeline.id: main-pipeline
  path.config: "/usr/share/logstash/pipeline/main-pipeline.conf"
  pipeline.workers: 2
  pipeline.batch.size: 125
  pipeline.batch.delay: 50
